"use client";

import { createApiAction } from "./api-action";

export type CatalogScope = "global" | "per_company";
export type ClassificationTable = "familias" | "grupos" | "subgrupos";
export type ClassificationInput = {
  id?: string;
  tabela: ClassificationTable;
  company_id: string | null;
  codigo: string;
  descricao: string;
};
export type SupplierInput = {
  id?: string;
  company_id: string | null;
  cnpj_cpf: string;
  tipo_pessoa?: string;
  razao_social: string;
  nome_fantasia?: string | null;
  inscricao_estadual?: string | null;
  inscricao_municipal?: string | null;
  email?: string | null;
  telefone?: string | null;
  cep?: string | null;
  logradouro?: string | null;
  numero?: string | null;
  complemento?: string | null;
  bairro?: string | null;
  municipio?: string | null;
  uf?: string | null;
  erp_system?: string | null;
  erp_code?: string | null;
  erp_external_id?: string | null;
  erp_metadata?: Record<string, unknown>;
};
export type ProdutoInput = {
  id?: string;
  company_id: string | null;
  codigo_interno: string;
  descricao: string;
  unidade: string;
  ean_gtin?: string | null;
  ncm: string;
  cest?: string | null;
  origem_mercadoria: number;
  familia_id?: string | null;
  grupo_id?: string | null;
  subgrupo_id?: string | null;
  ativo?: boolean;
};
export type ProdutoFornecedorInput = {
  id?: string;
  produto_id: string;
  fornecedor_id: string;
  codigo_item_nota: string;
  empresa_id?: string | null;
};
export type CentroCustoInput = {
  id?: string;
  company_id?: string | null;
  codigo: string;
  descricao: string;
  ativo?: boolean;
};
export type LocalEstoqueInput = {
  id?: string;
  company_id?: string | null;
  codigo: string;
  descricao: string;
  codigo_pai_id?: string | null;
  permite_movimentacao?: boolean;
  ativo?: boolean;
};
export type PlanoContasInput = {
  id?: string;
  company_id: string | null;
  conta_pai_id?: string | null;
  codigo: string;
  descricao: string;
  ativo?: boolean;
  permite_lancamentos?: boolean;
};
export type CompanyData = {
  status: string;
  cnpj: string;
  tipo?: string;
  abertura?: string;
  nome: string;
  fantasia?: string;
  uf: string;
  municipio: string;
  logradouro: string;
  numero: string;
  bairro: string;
  cep: string;
  email?: string;
  telefone?: string;
  situacao?: string;
  atividades_economicas?: Array<{ code: string; text: string; main?: boolean }>;
  atividades_secundarias?: Array<{ code: string; text: string }>;
  responsavel?: string;
  inscricao_estadual?: string;
  inscricao_municipal?: string;
};

export const getIntegracaoEmpresa = createApiAction("getIntegracaoEmpresa");
export const enviarCertificadoFiscal = createApiAction("enviarCertificadoFiscal");
export const salvarIntegracaoEmpresa = createApiAction("salvarIntegracaoEmpresa");
export const testarConexaoApfiscal = createApiAction("testarConexaoApfiscal");
export const sincronizarNfes = createApiAction("sincronizarNfes");
export const manifestarDocumentoFiscal = createApiAction("manifestarDocumentoFiscal");
export const baixarXmlDocumento = createApiAction("baixarXmlDocumento");
export const listCentrosCusto = createApiAction("listCentrosCusto");
export const saveCentroCusto = createApiAction<CentroCustoInput>("saveCentroCusto");
export const toggleCentroCustoAtivo = createApiAction("toggleCentroCustoAtivo");
export const deleteCentroCusto = createApiAction("deleteCentroCusto");
export const listClassifications = createApiAction("listClassifications");
export const saveClassification = createApiAction<ClassificationInput>("saveClassification");
export const deleteClassification = createApiAction("deleteClassification");
export const fetchCompanyByCnpj = createApiAction<{ cnpj: string }, CompanyData>(
  "fetchCompanyByCnpj",
);
export const fetchAddressByCep = createApiAction("fetchAddressByCep");
export const deleteFiscalDocuments = createApiAction("deleteFiscalDocuments");
export const getNfeDetails = createApiAction("getNfeDetails");
export const listLocaisEstoque = createApiAction("listLocaisEstoque");
export const saveLocalEstoque = createApiAction<LocalEstoqueInput>("saveLocalEstoque");
export const toggleLocalEstoqueAtivo = createApiAction("toggleLocalEstoqueAtivo");
export const deleteLocalEstoque = createApiAction("deleteLocalEstoque");
export const setPlanoContasCabecalho = createApiAction("setPlanoContasCabecalho");
export const setPlanoContasItem = createApiAction("setPlanoContasItem");
export const setLocalEstoqueCabecalho = createApiAction("setLocalEstoqueCabecalho");
export const setLocalEstoqueItem = createApiAction("setLocalEstoqueItem");
export const getAlocacaoNfe = createApiAction("getAlocacaoNfe");
export const setAlocacoesItem = createApiAction("setAlocacoesItem");
export const setAlocacoesCabecalho = createApiAction("setAlocacoesCabecalho");
export const setTipoCompraCabecalho = createApiAction("setTipoCompraCabecalho");
export const setTipoCompraItem = createApiAction("setTipoCompraItem");
export const restaurarTipoCompraItem = createApiAction("restaurarTipoCompraItem");
export const setCobrancaManual = createApiAction("setCobrancaManual");
export const sugerirApontamentosFinanceiros = createApiAction("sugerirApontamentosFinanceiros");
export const importNfeXml = createApiAction("importNfeXml");
export const aprovarNfe = createApiAction("aprovarNfe");
export const reavaliarStatusApontamentos = createApiAction("reavaliarStatusApontamentos");
export const marcarIntegradoTotvs = createApiAction("marcarIntegradoTotvs");
export const listStatusHistorico = createApiAction("listStatusHistorico");
export const getOrgSettings = createApiAction("getOrgSettings");
export const updateCatalogScope = createApiAction("updateCatalogScope");
export const listPlanoContas = createApiAction("listPlanoContas");
export const proximoCodigoPlanoContas = createApiAction("proximoCodigoPlanoContas");
export const savePlanoContas = createApiAction<PlanoContasInput>("savePlanoContas");
export const togglePlanoContasAtivo = createApiAction("togglePlanoContasAtivo");
export const deletePlanoContas = createApiAction("deletePlanoContas");
export const listProducts = createApiAction("listProducts");
export const getProduct = createApiAction("getProduct");
export const saveProduct = createApiAction<ProdutoInput>("saveProduct");
export const deleteProduct = createApiAction("deleteProduct");
export const deleteProducts = createApiAction("deleteProducts");
export const getNextProductCode = createApiAction("getNextProductCode");
export const listProductSuppliers = createApiAction("listProductSuppliers");
export const saveProductSupplier = createApiAction<ProdutoFornecedorInput>("saveProductSupplier");
export const deleteProductSupplier = createApiAction("deleteProductSupplier");
export const linkNfeItemToProduct = createApiAction("linkNfeItemToProduct");
export const unlinkNfeItem = createApiAction("unlinkNfeItem");
export const getNfeItemLinkContext = createApiAction("getNfeItemLinkContext");
export const searchProductsForLink = createApiAction("searchProductsForLink");
export const createProductAndLinkItem = createApiAction("createProductAndLinkItem");
export const listSuppliers = createApiAction("listSuppliers");
export const listSupplierFiscalDocuments = createApiAction("listSupplierFiscalDocuments");
export const saveSupplier = createApiAction<SupplierInput>("saveSupplier");
export const deleteSupplier = createApiAction("deleteSupplier");
export const deleteSuppliers = createApiAction("deleteSuppliers");
export const listTiposCompra = createApiAction("listTiposCompra");
