"use client";

import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Activity, Building2, Database, Loader2, Pencil, Play, RefreshCw, ShieldCheck, UserPlus, Users } from "lucide-react";
import { toast } from "sonner";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Checkbox } from "@/components/ui/checkbox";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Switch } from "@/components/ui/switch";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { getSuperadminDashboard, inviteAdminUser, syncAdminConnection, testAdminConnection, updateAdminCompanyConnection, updateAdminUser, updateAdminUserAccess, type AdminConnection } from "@/services/superadminService";

const emptyInvite = { fullName: "", email: "", organizationId: "", profileId: "", companyIds: [] as string[] };
const date = (value: string | null) => value ? new Date(value).toLocaleString("pt-BR") : "—";

export default function SuperadminPage() {
  const client = useQueryClient();
  const query = useQuery({ queryKey: ["superadmin"], queryFn: getSuperadminDashboard, refetchInterval: 20_000 });
  const [invite, setInvite] = useState<typeof emptyInvite | null>(null);
  const [edit, setEdit] = useState<{ id: string; fullName: string; active: boolean; planKey: string; maxCompanies: string; maxTotvsConnections: string; companyIds: string[] } | null>(null);
  const refresh = () => client.invalidateQueries({ queryKey: ["superadmin"] });
  const inviteMutation = useMutation({ mutationFn: inviteAdminUser, onSuccess: async () => { toast.success("Convite enviado."); setInvite(null); await refresh(); }, onError: (error: Error) => toast.error(error.message) });
  const userMutation = useMutation({ mutationFn: ({ id, ...input }: { id: string; fullName: string; active: boolean; planKey: string; maxCompanies: number | null; maxTotvsConnections: number | null }) => updateAdminUser(id, input), onSuccess: refresh, onError: (error: Error) => toast.error(error.message) });
  const editMutation = useMutation({ mutationFn: async (input: NonNullable<typeof edit>) => { await updateAdminUser(input.id, { fullName: input.fullName, active: input.active, planKey: input.planKey, maxCompanies: input.maxCompanies ? Number(input.maxCompanies) : null, maxTotvsConnections: input.maxTotvsConnections ? Number(input.maxTotvsConnections) : null }); await updateAdminUserAccess(input.id, input.companyIds); }, onSuccess: async () => { toast.success("Usuário atualizado."); setEdit(null); await refresh(); }, onError: (error: Error) => toast.error(error.message) });
  const companyMutation = useMutation({ mutationFn: ({ id, connectionKey, coligadaId }: { id: string; connectionKey: string | null; coligadaId: number | null }) => updateAdminCompanyConnection(id, { connectionKey, coligadaId }), onSuccess: async () => { toast.success("Vínculo TOTVS atualizado."); await refresh(); }, onError: (error: Error) => toast.error(error.message) });
  const testMutation = useMutation({ mutationFn: testAdminConnection, onSuccess: (result) => toast.success(`SELECT 1 confirmado em ${result.database}.`), onError: (error: Error) => toast.error(error.message) });
  const syncMutation = useMutation({ mutationFn: ({ organizationId, key }: { organizationId: string; key: string }) => syncAdminConnection(organizationId, key), onSuccess: () => toast.success("Sincronização adicionada à fila."), onError: (error: Error) => toast.error(error.message) });

  if (query.isLoading) return <div className="flex min-h-64 items-center justify-center text-sm text-slate-500"><Loader2 className="mr-2 h-5 w-5 animate-spin" />Carregando administração…</div>;
  if (query.isError || !query.data) return <Card className="border-red-200"><CardContent className="py-12 text-center text-red-700">Acesso indisponível ou restrito ao Super Admin.</CardContent></Card>;
  const data = query.data;
  return <div className="space-y-6">
    <header className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-sm font-semibold text-blue-700">Plataforma</p><h1 className="text-2xl font-bold tracking-tight">Administração do APFiscal</h1><p className="mt-1 text-sm text-slate-500">Usuários, empresas, bancos TOTVS e saúde das sincronizações.</p></div><div className="flex gap-2"><Button variant="outline" onClick={() => refresh()}><RefreshCw className="mr-2 h-4 w-4" />Atualizar</Button><Button onClick={() => setInvite({ ...emptyInvite })}><UserPlus className="mr-2 h-4 w-4" />Novo usuário</Button></div></header>
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
      <Metric icon={Users} label="Usuários" value={data.users.length} detail={`${data.users.filter((user) => user.active).length} ativos`} />
      <Metric icon={Building2} label="Empresas" value={data.companies.length} detail={`${data.organizations.length} organizações`} />
      <Metric icon={Database} label="Conexões TOTVS" value={data.connections.length} detail={`${data.connections.filter((item) => item.configured).length} configuradas`} />
      <Metric icon={Activity} label="Worker NF-e" value={data.scheduler.workers} detail={`${data.scheduler.schedulers.length} agendas`} />
    </div>
    <section><h2 className="mb-3 text-base font-semibold">Conexões disponíveis no ambiente</h2><div className="grid gap-3 lg:grid-cols-2">{data.connections.map((connection) => <ConnectionCard key={connection.key} connection={connection} companies={data.companies.filter((company) => company.totvs_connection_key === connection.key)} onTest={() => testMutation.mutate(connection.key)} onSync={(organizationId) => syncMutation.mutate({ organizationId, key: connection.key })} busy={testMutation.isPending || syncMutation.isPending} />)}</div></section>
    <Card><CardHeader><CardTitle className="text-base">Empresas e bancos TOTVS</CardTitle><CardDescription>Somente a chave e a coligada são persistidas; host, usuário e senha permanecem nos secrets.</CardDescription></CardHeader><CardContent className="overflow-x-auto"><Table className="min-w-[820px]"><TableHeader><TableRow><TableHead>Empresa</TableHead><TableHead>CNPJ</TableHead><TableHead>Conexão</TableHead><TableHead>Coligada</TableHead></TableRow></TableHeader><TableBody>{data.companies.map((company) => <CompanyRow key={company.id} company={company} connections={data.connections} onSave={(connectionKey, coligadaId) => companyMutation.mutate({ id: company.id, connectionKey, coligadaId })} />)}</TableBody></Table></CardContent></Card>
    <Card><CardHeader><CardTitle className="text-base">Usuários e planos</CardTitle></CardHeader><CardContent className="overflow-x-auto"><Table className="min-w-[820px]"><TableHeader><TableRow><TableHead>Usuário</TableHead><TableHead>Plano</TableHead><TableHead>Último acesso</TableHead><TableHead>Ativo</TableHead><TableHead className="text-right">Ações</TableHead></TableRow></TableHeader><TableBody>{data.users.map((user) => <TableRow key={user.id}><TableCell><div className="font-medium">{user.full_name || "Sem nome"}</div><div className="text-xs text-slate-500">{user.email}</div></TableCell><TableCell><Badge variant="outline">{user.plan_key}</Badge></TableCell><TableCell>{date(user.last_login_at)}</TableCell><TableCell><Switch disabled={user.is_superadmin || userMutation.isPending} checked={user.active} onCheckedChange={(active) => userMutation.mutate({ id: user.id, fullName: user.full_name || user.email, active, planKey: user.plan_key, maxCompanies: user.max_companies, maxTotvsConnections: user.max_totvs_connections })} /></TableCell><TableCell className="text-right"><Button size="sm" variant="ghost" disabled={user.is_superadmin} onClick={() => setEdit({ id: user.id, fullName: user.full_name || user.email, active: user.active, planKey: user.plan_key, maxCompanies: user.max_companies?.toString() ?? "", maxTotvsConnections: user.max_totvs_connections?.toString() ?? "", companyIds: data.companyAccess.filter((access) => access.user_id === user.id).map((access) => access.company_id) })}><Pencil className="mr-2 h-4 w-4" />Editar</Button></TableCell></TableRow>)}</TableBody></Table></CardContent></Card>
    <Card><CardHeader><CardTitle className="text-base">Execuções recentes</CardTitle></CardHeader><CardContent className="overflow-x-auto"><Table><TableHeader><TableRow><TableHead>Data</TableHead><TableHead>Conexão</TableHead><TableHead>Gatilho</TableHead><TableHead>Status</TableHead><TableHead>Erro</TableHead></TableRow></TableHeader><TableBody>{data.runs.slice(0, 20).map((run) => <TableRow key={run.id}><TableCell>{date(run.created_at)}</TableCell><TableCell className="font-mono text-xs">{run.connection_key || "—"}</TableCell><TableCell>{run.trigger}</TableCell><TableCell><Badge variant="outline">{run.status}</Badge></TableCell><TableCell className="max-w-80 truncate text-red-600">{run.error_message || "—"}</TableCell></TableRow>)}</TableBody></Table></CardContent></Card>
    <Dialog open={Boolean(invite)} onOpenChange={(open) => !open && setInvite(null)}><DialogContent><DialogHeader><DialogTitle>Convidar usuário</DialogTitle></DialogHeader>{invite && <div className="space-y-4"><div className="space-y-2"><Label>Nome completo</Label><Input value={invite.fullName} onChange={(event) => setInvite({ ...invite, fullName: event.target.value })} /></div><div className="space-y-2"><Label>E-mail</Label><Input type="email" value={invite.email} onChange={(event) => setInvite({ ...invite, email: event.target.value })} /></div><div className="space-y-2"><Label>Organização</Label><Select value={invite.organizationId} onValueChange={(organizationId) => setInvite({ ...invite, organizationId, profileId: "", companyIds: [] })}><SelectTrigger><SelectValue placeholder="Selecione" /></SelectTrigger><SelectContent>{data.organizations.map((org) => <SelectItem key={org.id} value={org.id}>{org.name}</SelectItem>)}</SelectContent></Select></div><div className="space-y-2"><Label>Perfil</Label><Select value={invite.profileId} onValueChange={(profileId) => setInvite({ ...invite, profileId })}><SelectTrigger><SelectValue placeholder="Selecione" /></SelectTrigger><SelectContent>{data.profiles.filter((profile) => profile.organization_id === invite.organizationId).map((profile) => <SelectItem key={profile.id} value={profile.id}>{profile.name}</SelectItem>)}</SelectContent></Select></div><CompanyChecks companies={data.companies.filter((company) => company.organization_id === invite.organizationId)} selected={invite.companyIds} onChange={(companyIds) => setInvite({ ...invite, companyIds })} /></div>}<DialogFooter><Button variant="outline" onClick={() => setInvite(null)}>Cancelar</Button><Button disabled={!invite?.fullName || !invite.email || !invite.organizationId || !invite.profileId || inviteMutation.isPending} onClick={() => invite && inviteMutation.mutate(invite)}>{inviteMutation.isPending && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}Enviar convite</Button></DialogFooter></DialogContent></Dialog>
    <Dialog open={Boolean(edit)} onOpenChange={(open) => !open && setEdit(null)}><DialogContent className="max-h-[90vh] overflow-y-auto"><DialogHeader><DialogTitle>Editar usuário</DialogTitle></DialogHeader>{edit && <div className="space-y-4"><div className="space-y-2"><Label>Nome</Label><Input value={edit.fullName} onChange={(event) => setEdit({ ...edit, fullName: event.target.value })} /></div><div className="grid grid-cols-2 gap-3"><div className="space-y-2"><Label>Plano</Label><Input value={edit.planKey} onChange={(event) => setEdit({ ...edit, planKey: event.target.value })} /></div><div className="flex items-end gap-2 pb-2"><Switch checked={edit.active} onCheckedChange={(active) => setEdit({ ...edit, active })} /><Label>Ativo</Label></div><div className="space-y-2"><Label>Máx. empresas</Label><Input type="number" min={1} value={edit.maxCompanies} onChange={(event) => setEdit({ ...edit, maxCompanies: event.target.value })} placeholder="Sem limite" /></div><div className="space-y-2"><Label>Máx. conexões</Label><Input type="number" min={1} value={edit.maxTotvsConnections} onChange={(event) => setEdit({ ...edit, maxTotvsConnections: event.target.value })} placeholder="Sem limite" /></div></div><CompanyChecks companies={data.companies} selected={edit.companyIds} onChange={(companyIds) => setEdit({ ...edit, companyIds })} /></div>}<DialogFooter><Button variant="outline" onClick={() => setEdit(null)}>Cancelar</Button><Button disabled={!edit?.fullName || !edit.planKey || editMutation.isPending} onClick={() => edit && editMutation.mutate(edit)}>{editMutation.isPending && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}Salvar</Button></DialogFooter></DialogContent></Dialog>
  </div>;
}

function Metric({ icon: Icon, label, value, detail }: { icon: typeof Users; label: string; value: number; detail: string }) { return <Card><CardContent className="flex items-center gap-3 p-4"><div className="rounded-lg bg-blue-50 p-2 text-blue-700"><Icon className="h-5 w-5" /></div><div><p className="text-xs text-slate-500">{label}</p><p className="text-xl font-bold">{value}</p><p className="text-xs text-slate-500">{detail}</p></div></CardContent></Card>; }
function ConnectionCard({ connection, companies, onTest, onSync, busy }: { connection: AdminConnection; companies: Array<{ organization_id: string; nome_fantasia: string | null; razao_social: string }>; onTest: () => void; onSync: (organizationId: string) => void; busy: boolean }) { const organizations = [...new Set(companies.map((company) => company.organization_id))]; return <Card><CardHeader className="pb-3"><div className="flex items-start justify-between"><div><CardTitle className="text-base">{connection.description}</CardTitle><CardDescription className="font-mono">{connection.key}</CardDescription></div><Badge variant={connection.configured ? "default" : "secondary"}>{connection.configured ? "Configurada" : "Incompleta"}</Badge></div></CardHeader><CardContent><div className="grid grid-cols-2 gap-3 text-sm"><div><p className="text-xs text-slate-500">Database</p><p className="font-medium">{connection.database || "—"}</p></div><div><p className="text-xs text-slate-500">Coligadas</p><p className="font-medium">{connection.coligadas.join(", ") || "—"}</p></div></div><p className="mt-3 text-xs text-slate-500">{companies.length} empresa(s) vinculada(s)</p><div className="mt-4 flex flex-wrap gap-2"><Button size="sm" variant="outline" disabled={!connection.configured || busy} onClick={onTest}><ShieldCheck className="mr-2 h-4 w-4" />Testar</Button>{organizations.map((organizationId) => <Button key={organizationId} size="sm" disabled={!connection.configured || busy} onClick={() => onSync(organizationId)}><Play className="mr-2 h-4 w-4" />Sincronizar</Button>)}</div></CardContent></Card>; }
function CompanyRow({ company, connections, onSave }: { company: { nome_fantasia: string | null; razao_social: string; cnpj: string; totvs_connection_key: string | null; totvs_coligada_id: number | null }; connections: AdminConnection[]; onSave: (key: string | null, coligada: number | null) => void }) { const [key, setKey] = useState(company.totvs_connection_key ?? "none"); const connection = connections.find((item) => item.key === key); return <TableRow><TableCell className="font-medium">{company.nome_fantasia || company.razao_social}</TableCell><TableCell className="font-mono text-xs">{company.cnpj}</TableCell><TableCell><Select value={key} onValueChange={(value) => { setKey(value); if (value === "none") onSave(null, null); }}><SelectTrigger className="w-52"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="none">Sem conexão</SelectItem>{connections.map((item) => <SelectItem key={item.key} value={item.key}>{item.description}</SelectItem>)}</SelectContent></Select></TableCell><TableCell><Select value={company.totvs_connection_key === key && company.totvs_coligada_id ? String(company.totvs_coligada_id) : "none"} disabled={!connection} onValueChange={(value) => value !== "none" && onSave(key, Number(value))}><SelectTrigger className="w-36"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="none">Selecione</SelectItem>{connection?.coligadas.map((id) => <SelectItem key={id} value={String(id)}>Coligada {id}</SelectItem>)}</SelectContent></Select></TableCell></TableRow>; }
function CompanyChecks({ companies, selected, onChange }: { companies: Array<{ id: string; nome_fantasia: string | null; razao_social: string }>; selected: string[]; onChange: (ids: string[]) => void }) { return <div className="space-y-2"><Label>Empresas permitidas</Label><div className="max-h-40 space-y-2 overflow-y-auto rounded-md border p-3">{companies.length ? companies.map((company) => <label key={company.id} className="flex items-center gap-2 text-sm"><Checkbox checked={selected.includes(company.id)} onCheckedChange={(checked) => onChange(checked ? [...selected, company.id] : selected.filter((id) => id !== company.id))} />{company.nome_fantasia || company.razao_social}</label>) : <p className="text-xs text-slate-500">Selecione uma organização.</p>}</div></div>; }
