/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSuppliersRouteImport } from './routes/_authenticated/suppliers'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedProductsRouteImport } from './routes/_authenticated/products'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedNfeIntegracaoRouteImport } from './routes/_authenticated/nfe-integracao'
import { Route as AuthenticatedMonitoringRouteImport } from './routes/_authenticated/monitoring'
import { Route as AuthenticatedDocumentsRouteImport } from './routes/_authenticated/documents'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCompaniesRouteImport } from './routes/_authenticated/companies'
import { Route as AuthenticatedClassificationsRouteImport } from './routes/_authenticated/classifications'
import { Route as AuthenticatedSettingsPlanoContasRouteImport } from './routes/_authenticated/settings.plano-contas'
import { Route as AuthenticatedSettingsMembersRouteImport } from './routes/_authenticated/settings.members'
import { Route as AuthenticatedSettingsLocaisEstoqueRouteImport } from './routes/_authenticated/settings.locais-estoque'
import { Route as AuthenticatedSettingsCentrosCustoRouteImport } from './routes/_authenticated/settings.centros-custo'
import { Route as AuthenticatedSettingsCatalogRouteImport } from './routes/_authenticated/settings.catalog'
import { Route as AuthenticatedSettingsApiRouteImport } from './routes/_authenticated/settings.api'
import { Route as AuthenticatedDocumentsNfseRouteImport } from './routes/_authenticated/documents.nfse'
import { Route as AuthenticatedDocumentsCteRouteImport } from './routes/_authenticated/documents.cte'
import { Route as AuthenticatedDocumentsNfeIndexRouteImport } from './routes/_authenticated/documents.nfe.index'
import { Route as ApiPublicHooksApfiscalXmlRetryRouteImport } from './routes/api/public/hooks/apfiscal-xml-retry'
import { Route as AuthenticatedDocumentsNfeNfeIdRouteImport } from './routes/_authenticated/documents.nfe.$nfeId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSuppliersRoute = AuthenticatedSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProductsRoute = AuthenticatedProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedNfeIntegracaoRoute =
  AuthenticatedNfeIntegracaoRouteImport.update({
    id: '/nfe-integracao',
    path: '/nfe-integracao',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMonitoringRoute = AuthenticatedMonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDocumentsRoute = AuthenticatedDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCompaniesRoute = AuthenticatedCompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedClassificationsRoute =
  AuthenticatedClassificationsRouteImport.update({
    id: '/classifications',
    path: '/classifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsPlanoContasRoute =
  AuthenticatedSettingsPlanoContasRouteImport.update({
    id: '/plano-contas',
    path: '/plano-contas',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsMembersRoute =
  AuthenticatedSettingsMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsLocaisEstoqueRoute =
  AuthenticatedSettingsLocaisEstoqueRouteImport.update({
    id: '/locais-estoque',
    path: '/locais-estoque',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsCentrosCustoRoute =
  AuthenticatedSettingsCentrosCustoRouteImport.update({
    id: '/centros-custo',
    path: '/centros-custo',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsCatalogRoute =
  AuthenticatedSettingsCatalogRouteImport.update({
    id: '/catalog',
    path: '/catalog',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsApiRoute =
  AuthenticatedSettingsApiRouteImport.update({
    id: '/api',
    path: '/api',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedDocumentsNfseRoute =
  AuthenticatedDocumentsNfseRouteImport.update({
    id: '/nfse',
    path: '/nfse',
    getParentRoute: () => AuthenticatedDocumentsRoute,
  } as any)
const AuthenticatedDocumentsCteRoute =
  AuthenticatedDocumentsCteRouteImport.update({
    id: '/cte',
    path: '/cte',
    getParentRoute: () => AuthenticatedDocumentsRoute,
  } as any)
const AuthenticatedDocumentsNfeIndexRoute =
  AuthenticatedDocumentsNfeIndexRouteImport.update({
    id: '/nfe/',
    path: '/nfe/',
    getParentRoute: () => AuthenticatedDocumentsRoute,
  } as any)
const ApiPublicHooksApfiscalXmlRetryRoute =
  ApiPublicHooksApfiscalXmlRetryRouteImport.update({
    id: '/api/public/hooks/apfiscal-xml-retry',
    path: '/api/public/hooks/apfiscal-xml-retry',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedDocumentsNfeNfeIdRoute =
  AuthenticatedDocumentsNfeNfeIdRouteImport.update({
    id: '/nfe/$nfeId',
    path: '/nfe/$nfeId',
    getParentRoute: () => AuthenticatedDocumentsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/classifications': typeof AuthenticatedClassificationsRoute
  '/companies': typeof AuthenticatedCompaniesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documents': typeof AuthenticatedDocumentsRouteWithChildren
  '/monitoring': typeof AuthenticatedMonitoringRoute
  '/nfe-integracao': typeof AuthenticatedNfeIntegracaoRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/products': typeof AuthenticatedProductsRoute
  '/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/suppliers': typeof AuthenticatedSuppliersRoute
  '/documents/cte': typeof AuthenticatedDocumentsCteRoute
  '/documents/nfse': typeof AuthenticatedDocumentsNfseRoute
  '/settings/api': typeof AuthenticatedSettingsApiRoute
  '/settings/catalog': typeof AuthenticatedSettingsCatalogRoute
  '/settings/centros-custo': typeof AuthenticatedSettingsCentrosCustoRoute
  '/settings/locais-estoque': typeof AuthenticatedSettingsLocaisEstoqueRoute
  '/settings/members': typeof AuthenticatedSettingsMembersRoute
  '/settings/plano-contas': typeof AuthenticatedSettingsPlanoContasRoute
  '/documents/nfe/$nfeId': typeof AuthenticatedDocumentsNfeNfeIdRoute
  '/api/public/hooks/apfiscal-xml-retry': typeof ApiPublicHooksApfiscalXmlRetryRoute
  '/documents/nfe/': typeof AuthenticatedDocumentsNfeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/classifications': typeof AuthenticatedClassificationsRoute
  '/companies': typeof AuthenticatedCompaniesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documents': typeof AuthenticatedDocumentsRouteWithChildren
  '/monitoring': typeof AuthenticatedMonitoringRoute
  '/nfe-integracao': typeof AuthenticatedNfeIntegracaoRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/products': typeof AuthenticatedProductsRoute
  '/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/suppliers': typeof AuthenticatedSuppliersRoute
  '/documents/cte': typeof AuthenticatedDocumentsCteRoute
  '/documents/nfse': typeof AuthenticatedDocumentsNfseRoute
  '/settings/api': typeof AuthenticatedSettingsApiRoute
  '/settings/catalog': typeof AuthenticatedSettingsCatalogRoute
  '/settings/centros-custo': typeof AuthenticatedSettingsCentrosCustoRoute
  '/settings/locais-estoque': typeof AuthenticatedSettingsLocaisEstoqueRoute
  '/settings/members': typeof AuthenticatedSettingsMembersRoute
  '/settings/plano-contas': typeof AuthenticatedSettingsPlanoContasRoute
  '/documents/nfe/$nfeId': typeof AuthenticatedDocumentsNfeNfeIdRoute
  '/api/public/hooks/apfiscal-xml-retry': typeof ApiPublicHooksApfiscalXmlRetryRoute
  '/documents/nfe': typeof AuthenticatedDocumentsNfeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authenticated/classifications': typeof AuthenticatedClassificationsRoute
  '/_authenticated/companies': typeof AuthenticatedCompaniesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/documents': typeof AuthenticatedDocumentsRouteWithChildren
  '/_authenticated/monitoring': typeof AuthenticatedMonitoringRoute
  '/_authenticated/nfe-integracao': typeof AuthenticatedNfeIntegracaoRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/products': typeof AuthenticatedProductsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/_authenticated/suppliers': typeof AuthenticatedSuppliersRoute
  '/_authenticated/documents/cte': typeof AuthenticatedDocumentsCteRoute
  '/_authenticated/documents/nfse': typeof AuthenticatedDocumentsNfseRoute
  '/_authenticated/settings/api': typeof AuthenticatedSettingsApiRoute
  '/_authenticated/settings/catalog': typeof AuthenticatedSettingsCatalogRoute
  '/_authenticated/settings/centros-custo': typeof AuthenticatedSettingsCentrosCustoRoute
  '/_authenticated/settings/locais-estoque': typeof AuthenticatedSettingsLocaisEstoqueRoute
  '/_authenticated/settings/members': typeof AuthenticatedSettingsMembersRoute
  '/_authenticated/settings/plano-contas': typeof AuthenticatedSettingsPlanoContasRoute
  '/_authenticated/documents/nfe/$nfeId': typeof AuthenticatedDocumentsNfeNfeIdRoute
  '/api/public/hooks/apfiscal-xml-retry': typeof ApiPublicHooksApfiscalXmlRetryRoute
  '/_authenticated/documents/nfe/': typeof AuthenticatedDocumentsNfeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/classifications'
    | '/companies'
    | '/dashboard'
    | '/documents'
    | '/monitoring'
    | '/nfe-integracao'
    | '/notifications'
    | '/products'
    | '/settings'
    | '/suppliers'
    | '/documents/cte'
    | '/documents/nfse'
    | '/settings/api'
    | '/settings/catalog'
    | '/settings/centros-custo'
    | '/settings/locais-estoque'
    | '/settings/members'
    | '/settings/plano-contas'
    | '/documents/nfe/$nfeId'
    | '/api/public/hooks/apfiscal-xml-retry'
    | '/documents/nfe/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/classifications'
    | '/companies'
    | '/dashboard'
    | '/documents'
    | '/monitoring'
    | '/nfe-integracao'
    | '/notifications'
    | '/products'
    | '/settings'
    | '/suppliers'
    | '/documents/cte'
    | '/documents/nfse'
    | '/settings/api'
    | '/settings/catalog'
    | '/settings/centros-custo'
    | '/settings/locais-estoque'
    | '/settings/members'
    | '/settings/plano-contas'
    | '/documents/nfe/$nfeId'
    | '/api/public/hooks/apfiscal-xml-retry'
    | '/documents/nfe'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/register'
    | '/_authenticated/classifications'
    | '/_authenticated/companies'
    | '/_authenticated/dashboard'
    | '/_authenticated/documents'
    | '/_authenticated/monitoring'
    | '/_authenticated/nfe-integracao'
    | '/_authenticated/notifications'
    | '/_authenticated/products'
    | '/_authenticated/settings'
    | '/_authenticated/suppliers'
    | '/_authenticated/documents/cte'
    | '/_authenticated/documents/nfse'
    | '/_authenticated/settings/api'
    | '/_authenticated/settings/catalog'
    | '/_authenticated/settings/centros-custo'
    | '/_authenticated/settings/locais-estoque'
    | '/_authenticated/settings/members'
    | '/_authenticated/settings/plano-contas'
    | '/_authenticated/documents/nfe/$nfeId'
    | '/api/public/hooks/apfiscal-xml-retry'
    | '/_authenticated/documents/nfe/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ApiPublicHooksApfiscalXmlRetryRoute: typeof ApiPublicHooksApfiscalXmlRetryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/suppliers': {
      id: '/_authenticated/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof AuthenticatedSuppliersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/products': {
      id: '/_authenticated/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AuthenticatedProductsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/nfe-integracao': {
      id: '/_authenticated/nfe-integracao'
      path: '/nfe-integracao'
      fullPath: '/nfe-integracao'
      preLoaderRoute: typeof AuthenticatedNfeIntegracaoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/monitoring': {
      id: '/_authenticated/monitoring'
      path: '/monitoring'
      fullPath: '/monitoring'
      preLoaderRoute: typeof AuthenticatedMonitoringRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/documents': {
      id: '/_authenticated/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthenticatedDocumentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/companies': {
      id: '/_authenticated/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof AuthenticatedCompaniesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/classifications': {
      id: '/_authenticated/classifications'
      path: '/classifications'
      fullPath: '/classifications'
      preLoaderRoute: typeof AuthenticatedClassificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/plano-contas': {
      id: '/_authenticated/settings/plano-contas'
      path: '/plano-contas'
      fullPath: '/settings/plano-contas'
      preLoaderRoute: typeof AuthenticatedSettingsPlanoContasRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/members': {
      id: '/_authenticated/settings/members'
      path: '/members'
      fullPath: '/settings/members'
      preLoaderRoute: typeof AuthenticatedSettingsMembersRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/locais-estoque': {
      id: '/_authenticated/settings/locais-estoque'
      path: '/locais-estoque'
      fullPath: '/settings/locais-estoque'
      preLoaderRoute: typeof AuthenticatedSettingsLocaisEstoqueRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/centros-custo': {
      id: '/_authenticated/settings/centros-custo'
      path: '/centros-custo'
      fullPath: '/settings/centros-custo'
      preLoaderRoute: typeof AuthenticatedSettingsCentrosCustoRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/catalog': {
      id: '/_authenticated/settings/catalog'
      path: '/catalog'
      fullPath: '/settings/catalog'
      preLoaderRoute: typeof AuthenticatedSettingsCatalogRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/api': {
      id: '/_authenticated/settings/api'
      path: '/api'
      fullPath: '/settings/api'
      preLoaderRoute: typeof AuthenticatedSettingsApiRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/documents/nfse': {
      id: '/_authenticated/documents/nfse'
      path: '/nfse'
      fullPath: '/documents/nfse'
      preLoaderRoute: typeof AuthenticatedDocumentsNfseRouteImport
      parentRoute: typeof AuthenticatedDocumentsRoute
    }
    '/_authenticated/documents/cte': {
      id: '/_authenticated/documents/cte'
      path: '/cte'
      fullPath: '/documents/cte'
      preLoaderRoute: typeof AuthenticatedDocumentsCteRouteImport
      parentRoute: typeof AuthenticatedDocumentsRoute
    }
    '/_authenticated/documents/nfe/': {
      id: '/_authenticated/documents/nfe/'
      path: '/nfe'
      fullPath: '/documents/nfe/'
      preLoaderRoute: typeof AuthenticatedDocumentsNfeIndexRouteImport
      parentRoute: typeof AuthenticatedDocumentsRoute
    }
    '/api/public/hooks/apfiscal-xml-retry': {
      id: '/api/public/hooks/apfiscal-xml-retry'
      path: '/api/public/hooks/apfiscal-xml-retry'
      fullPath: '/api/public/hooks/apfiscal-xml-retry'
      preLoaderRoute: typeof ApiPublicHooksApfiscalXmlRetryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/documents/nfe/$nfeId': {
      id: '/_authenticated/documents/nfe/$nfeId'
      path: '/nfe/$nfeId'
      fullPath: '/documents/nfe/$nfeId'
      preLoaderRoute: typeof AuthenticatedDocumentsNfeNfeIdRouteImport
      parentRoute: typeof AuthenticatedDocumentsRoute
    }
  }
}

interface AuthenticatedDocumentsRouteChildren {
  AuthenticatedDocumentsCteRoute: typeof AuthenticatedDocumentsCteRoute
  AuthenticatedDocumentsNfseRoute: typeof AuthenticatedDocumentsNfseRoute
  AuthenticatedDocumentsNfeNfeIdRoute: typeof AuthenticatedDocumentsNfeNfeIdRoute
  AuthenticatedDocumentsNfeIndexRoute: typeof AuthenticatedDocumentsNfeIndexRoute
}

const AuthenticatedDocumentsRouteChildren: AuthenticatedDocumentsRouteChildren =
  {
    AuthenticatedDocumentsCteRoute: AuthenticatedDocumentsCteRoute,
    AuthenticatedDocumentsNfseRoute: AuthenticatedDocumentsNfseRoute,
    AuthenticatedDocumentsNfeNfeIdRoute: AuthenticatedDocumentsNfeNfeIdRoute,
    AuthenticatedDocumentsNfeIndexRoute: AuthenticatedDocumentsNfeIndexRoute,
  }

const AuthenticatedDocumentsRouteWithChildren =
  AuthenticatedDocumentsRoute._addFileChildren(
    AuthenticatedDocumentsRouteChildren,
  )

interface AuthenticatedSettingsRouteChildren {
  AuthenticatedSettingsApiRoute: typeof AuthenticatedSettingsApiRoute
  AuthenticatedSettingsCatalogRoute: typeof AuthenticatedSettingsCatalogRoute
  AuthenticatedSettingsCentrosCustoRoute: typeof AuthenticatedSettingsCentrosCustoRoute
  AuthenticatedSettingsLocaisEstoqueRoute: typeof AuthenticatedSettingsLocaisEstoqueRoute
  AuthenticatedSettingsMembersRoute: typeof AuthenticatedSettingsMembersRoute
  AuthenticatedSettingsPlanoContasRoute: typeof AuthenticatedSettingsPlanoContasRoute
}

const AuthenticatedSettingsRouteChildren: AuthenticatedSettingsRouteChildren = {
  AuthenticatedSettingsApiRoute: AuthenticatedSettingsApiRoute,
  AuthenticatedSettingsCatalogRoute: AuthenticatedSettingsCatalogRoute,
  AuthenticatedSettingsCentrosCustoRoute:
    AuthenticatedSettingsCentrosCustoRoute,
  AuthenticatedSettingsLocaisEstoqueRoute:
    AuthenticatedSettingsLocaisEstoqueRoute,
  AuthenticatedSettingsMembersRoute: AuthenticatedSettingsMembersRoute,
  AuthenticatedSettingsPlanoContasRoute: AuthenticatedSettingsPlanoContasRoute,
}

const AuthenticatedSettingsRouteWithChildren =
  AuthenticatedSettingsRoute._addFileChildren(
    AuthenticatedSettingsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedClassificationsRoute: typeof AuthenticatedClassificationsRoute
  AuthenticatedCompaniesRoute: typeof AuthenticatedCompaniesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDocumentsRoute: typeof AuthenticatedDocumentsRouteWithChildren
  AuthenticatedMonitoringRoute: typeof AuthenticatedMonitoringRoute
  AuthenticatedNfeIntegracaoRoute: typeof AuthenticatedNfeIntegracaoRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedProductsRoute: typeof AuthenticatedProductsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRouteWithChildren
  AuthenticatedSuppliersRoute: typeof AuthenticatedSuppliersRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedClassificationsRoute: AuthenticatedClassificationsRoute,
  AuthenticatedCompaniesRoute: AuthenticatedCompaniesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDocumentsRoute: AuthenticatedDocumentsRouteWithChildren,
  AuthenticatedMonitoringRoute: AuthenticatedMonitoringRoute,
  AuthenticatedNfeIntegracaoRoute: AuthenticatedNfeIntegracaoRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedProductsRoute: AuthenticatedProductsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRouteWithChildren,
  AuthenticatedSuppliersRoute: AuthenticatedSuppliersRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ApiPublicHooksApfiscalXmlRetryRoute: ApiPublicHooksApfiscalXmlRetryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
